chore: add ns validation to CI (#184)
Signed-off-by: Tommy Hughes <tohughes@redhat.com>

diff --git a/.github/actions/kind/action.yaml b/.github/actions/kind/action.yaml
--- a/.github/actions/kind/action.yaml
+++ b/.github/actions/kind/action.yaml
@@ -38,7 +38,15 @@ runs:
 
     - name: Push local images to the local registry
       run: make push-all-images REGISTRY=localhost:5001 PUSH_EXTRA_AGRS="--tls-verify=false"
-      shell: bash  
+      shell: bash
+
+    - name: Create namespace
+      run: make namespace NAMESPACE=${{inputs.namespace}}
+      shell: bash
+
+    - name: Validate namespace exists
+      run: kubectl get namespace ${{inputs.namespace}} || (echo "Error: Namespace ${{inputs.namespace}} does not exist" && exit 1)
+      shell: bash
 
     - name: Helm Install (using local registry)
       run: make helm-install-test NAMESPACE=${{inputs.namespace}} REGISTRY=localhost:5001 LLM=${{inputs.llm}} LLM_ID=${{inputs.llm_id}} LLM_URL=${{inputs.llm_url}} LLM_API_TOKEN=$LLM_API_TOKEN EXTRA_HELM_ARGS="--set requestManagement.networkPolicies.platform=kind --set requestManagement.requestManager.externalAccess.enabled=false --set requestManagement.integrationDispatcher.externalAccess.enabled=false"
