chore: remove personal user from mock data (#183)
* chore: remove personal user from mock data

Signed-off-by: Tommy Hughes <tohughes@redhat.com>

* chore: add ns validation to CI

Signed-off-by: Tommy Hughes <tohughes@redhat.com>

---------

Signed-off-by: Tommy Hughes <tohughes@redhat.com>

diff --git a/.github/actions/kind/action.yaml b/.github/actions/kind/action.yaml
--- a/.github/actions/kind/action.yaml
+++ b/.github/actions/kind/action.yaml
@@ -45,7 +45,11 @@ runs:
       shell: bash
 
     - name: Validate namespace exists
-      run: kubectl get namespace ${{inputs.namespace}} || (echo "Error: Namespace ${{inputs.namespace}} does not exist" && exit 1)
+      run: |
+        if ! kubectl get namespace ${{inputs.namespace}}; then
+          echo "Error: Namespace ${{inputs.namespace}} does not exist"
+          exit 1
+        fi
       shell: bash
 
     - name: Helm Install (using local registry)
